/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package backup;
import student_management_system.*;
import com.mysql.cj.jdbc.ConnectionImpl;
import com.mysql.cj.jdbc.StatementImpl;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author sdddd
 */
public class main_menu extends javax.swing.JFrame {

    /**
     * Creates new form main_menu
     */
    public main_menu() {
        initComponents();
    }
    String[] get_name_dept()
    {
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://sql6.freesqldatabase.com:3306/sql6518757","sql6518757","jXZABmjPLt");
            ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://localhost:3306/project_sms","root","2580");
            StatementImpl st= (StatementImpl)conn.createStatement();
            String sql="select count(*) from dept";//select * from admin where username='sdd'
            ResultSet rs=st.executeQuery(sql);
            //while(rs.next()){ // no need while loop cause there are condition in query username='user' 
            rs.next();
                int x= rs.getInt("count(*)");
            sql="select * from dept";
            rs=st.executeQuery(sql);
            String result[]=new String[x];
            int i=0;
            while(rs.next())
                result[i++]=rs.getString("dept");
            return result;
        }
        catch(Exception e){
            return new String[] {"None"};
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_menu = new JPanel();
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jTabbedPane1 = new JTabbedPane();
        panel_search = new java.awt.Panel();
        jPanel1 = new JPanel();
        jPanel3 = new JPanel();
        panal1_button_search = new JButton();
        search_std_id = new JTextField();
        jPanel2 = new JPanel();
        name = new JLabel();
        src_name = new JLabel();
        dept = new JLabel();
        src_dept = new JLabel();
        id = new JLabel();
        src_id = new JLabel();
        cgpa = new JLabel();
        src_cgpa = new JLabel();
        credit = new JLabel();
        src_credit = new JLabel();
        jButton1 = new JButton();
        src_note = new JLabel();
        panel_add = new java.awt.Panel();
        add_labal1 = new JLabel();
        add_std_id = new JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        add_std_name = new JTextField();
        add_student = new JButton();
        add_std_note = new JLabel();
        add_std_dept = new JComboBox<>();
        banner = new JPanel();
        jLabel1 = new JLabel();
        l_result = new JLabel();
        jLabel7 = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(getPreferredSize());
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        main_menu.setBackground(new java.awt.Color(255, 255, 255));
        main_menu.setPreferredSize(new java.awt.Dimension(900, 500));
        main_menu.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(900, 400));

        panel_search.setBackground(new java.awt.Color(255, 255, 255));
        panel_search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_search.setPreferredSize(new java.awt.Dimension(900, 362));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 0));

        panal1_button_search.setFont(new java.awt.Font("Segoe UI", 0, 14));  
        panal1_button_search.setForeground(new java.awt.Color(0, 0, 204));
        panal1_button_search.setText("Search");
        panal1_button_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panal1_button_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panal1_button_searchMouseExited(evt);
            }
        });
        panal1_button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panal1_button_searchActionPerformed(evt);
            }
        });

        search_std_id.setFont(new java.awt.Font("Segoe UI", 0, 14));  
        search_std_id.setBorder(javax.swing.BorderFactory.createTitledBorder(new border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Student ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 204)));  
        search_std_id.setMinimumSize(new java.awt.Dimension(80, 30));
        search_std_id.setPreferredSize(new java.awt.Dimension(80, 30));
        search_std_id.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                search_std_idCaretUpdate(evt);
            }
        });
        search_std_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_std_idActionPerformed(evt);
            }
        });
        search_std_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_std_idKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        name.setFont(new java.awt.Font("Serif", 1, 14));  

        src_name.setFont(new java.awt.Font("Serif", 0, 14));  

        dept.setFont(new java.awt.Font("Serif", 1, 14));  

        src_dept.setFont(new java.awt.Font("Serif", 0, 14));  

        id.setFont(new java.awt.Font("Serif", 1, 14));  

        src_id.setFont(new java.awt.Font("Serif", 0, 14));  

        cgpa.setFont(new java.awt.Font("Serif", 1, 14));  

        src_cgpa.setFont(new java.awt.Font("Serif", 0, 14));  

        credit.setFont(new java.awt.Font("Serif", 1, 14));  

        src_credit.setFont(new java.awt.Font("Serif", 0, 14));  

        javax.swing.GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cgpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(credit, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(src_name, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(src_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(src_id, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(src_cgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(src_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(src_name, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(src_dept, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(src_id, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cgpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(src_cgpa, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(credit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(src_credit, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        src_note.setBackground(new java.awt.Color(255, 255, 255));
        src_note.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search_std_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(panal1_button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(src_note, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(search_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(src_note, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panal1_button_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(208, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_searchLayout = new GroupLayout(panel_search);
        panel_search.setLayout(panel_searchLayout);
        panel_searchLayout.setHorizontalGroup(
            panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        panel_searchLayout.setVerticalGroup(
            panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search", panel_search);

        panel_add.setBackground(new java.awt.Color(255, 255, 255));

        add_labal1.setBackground(new java.awt.Color(255, 255, 255));
        add_labal1.setFont(new java.awt.Font("Segoe UI", 0, 14));  
        add_labal1.setText("ID :");

        add_std_id.setFont(new java.awt.Font("Segoe UI", 0, 14));  
        add_std_id.setMinimumSize(new java.awt.Dimension(77, 26));
        add_std_id.setPreferredSize(new java.awt.Dimension(77, 26));
        add_std_id.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                add_std_idCaretUpdate(evt);
            }
        });
        add_std_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_std_idActionPerformed(evt);
            }
        });
        add_std_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                add_std_idKeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));  
        jLabel2.setText("Dept : ");
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));  
        jLabel3.setText("Name : ");

        add_std_name.setFont(new java.awt.Font("Segoe UI", 0, 14));  
        add_std_name.setMinimumSize(new java.awt.Dimension(77, 26));
        add_std_name.setPreferredSize(new java.awt.Dimension(77, 26));
        add_std_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_std_nameActionPerformed(evt);
            }
        });

        add_student.setText("Add Student");
        add_student.setMaximumSize(new java.awt.Dimension(77, 26));
        add_student.setMinimumSize(new java.awt.Dimension(77, 26));
        add_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_studentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_studentMouseExited(evt);
            }
        });
        add_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_studentActionPerformed(evt);
            }
        });

        add_std_note.setBackground(new java.awt.Color(255, 255, 255));
        add_std_note.setFont(new java.awt.Font("Segoe UI", 2, 14));  
        add_std_note.setForeground(new java.awt.Color(0, 0, 255));
        add_std_note.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        add_std_dept.setModel(Server.get_dept_list());
        add_std_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_std_deptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_addLayout = new GroupLayout(panel_add);
        panel_add.setLayout(panel_addLayout);
        panel_addLayout.setHorizontalGroup(
            panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_std_note, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_addLayout.createSequentialGroup()
                        .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(add_labal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_std_id, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(add_std_name, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(add_student, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(add_std_dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        panel_addLayout.setVerticalGroup(
            panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addLayout.createSequentialGroup()
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(add_labal1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(add_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_std_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_std_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(add_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(add_std_note, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Add", panel_add);

        jPanel2.add(jTabbedPane1);

        banner.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/student_management_system/neub.png")));  

        l_result.setBackground(new java.awt.Color(255, 255, 255));
        l_result.setFont(new java.awt.Font("Segoe UI", 1, 36));  
        l_result.setForeground(new java.awt.Color(79, 171, 98));
        l_result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_result.setText("NORTH EAST UNIVERSITY BANGLADESH");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24));  
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Student management System");

        javax.swing.GroupLayout bannerLayout = new GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bannerLayout.createSequentialGroup()
                        .addComponent(l_result, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_menu.add(jPanel1);

        getContentPane().add(main_menu);
        main_menu.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_std_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_std_idActionPerformed
        
    }//GEN-LAST:event_add_std_idActionPerformed

    private void add_std_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_std_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_std_nameActionPerformed

    private void add_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_studentActionPerformed
        // TODO add your handling code here:
        
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://sql6.freesqldatabase.com:3306/sql6518757","sql6518757","jXZABmjPLt");
            ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://localhost:3306/project_sms","root","2580");
            String sql="insert into `student`(`std_id`, `std_name`, `dept`, `std_cgpa`, `std_credit`, `std_gpa`) values(?,?,?,?,?,?)";
            //System.out.println("Line 5");
            PreparedStatement ps = conn.prepareStatement(sql);
            //System.out.println("Line 6");
            ps.setString(1, add_std_id.getText());
            ps.setString(2, add_std_name.getText());
            ps.setString(3, add_std_dept.getSelectedItem().toString());
            ps.setString(4, "0");
            ps.setString(5, "0");
            ps.setString(6, "0");
            //System.out.println(sql);
            ps.executeUpdate();
            add_std_id.setText("");
            add_std_name.setText(""); 
            add_std_dept.setSelectedItem("None");
            add_std_note.setText("");
            add_std_note.setText("Student added.");
            String ss;
            
        }
        catch(Exception e){
            add_std_note.setText("Sorry something went wrong.");
        }
    }//GEN-LAST:event_add_studentActionPerformed

    private void add_std_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_std_idKeyPressed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://sql6.freesqldatabase.com:3306/sql6518757","sql6518757","jXZABmjPLt");
            ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://localhost:3306/sms","root","2580");
            StatementImpl sql= (StatementImpl)conn.createStatement();
            String str="select * from `student` where id=" +add_std_id.getText();
            //System.out.println(str);
            ResultSet rs= sql.executeQuery(str);
            rs.next();
            String id = rs.getString("std_id");
            //System.out.println("id= "+id);
            if(add_std_id.getText().equals(id)){
              add_std_name.setText(rs.getString("std_name")); 
              //System.out.println("jjjjj"+id);
                add_std_dept.setSelectedItem(rs.getString("std_dept"));
                add_std_note.setText("Student already exist.");
            }
            else
            {
                add_std_note.setText("");
                add_std_name.setText(""); 
                add_std_dept.setSelectedItem("");
            }
        }catch(Exception e){
            add_std_note.setText("");
            add_std_name.setText(""); 
            add_std_dept.setSelectedItem("");
        }
    }//GEN-LAST:event_add_std_idKeyPressed

    private void add_studentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_studentMouseEntered
        // TODO add your handling code here:
        add_student.setBackground(new java.awt.Color(153,153,255));
    }//GEN-LAST:event_add_studentMouseEntered

    private void add_studentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_studentMouseExited
        // TODO add your handling code here:
        add_student.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_add_studentMouseExited

    private void search_std_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_std_idActionPerformed
        // TODO add your handling code here:
        panal1_button_searchActionPerformed(evt);
    }//GEN-LAST:event_search_std_idActionPerformed

    private void search_std_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_std_idKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_std_idKeyPressed

    private void panal1_button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panal1_button_searchActionPerformed
        // TODO add your handling code here:
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://sql6.freesqldatabase.com:3306/sql6518757","sql6518757","jXZABmjPLt");
            ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","2580");
            StatementImpl st= (StatementImpl)conn.createStatement();
            String sql="select * from student where std_id='" + search_std_id.getText() +"'";//select * from admin where username='sdd'
            ResultSet rs=st.executeQuery(sql);
            //while(rs.next()){ // no need while loop cause there are condition in query username='user' 
            rs.next();

                //System.out.println(std_name+" "+std_dept);
                name.setText("Name :");
                dept.setText("Dept :");
                id.setText("ID :");
                cgpa.setText("CGPA :");
                credit.setText("Credit :");
                src_name.setText(rs.getString("std_name"));
                src_dept.setText(rs.getString("std_id"));
                src_id.setText(rs.getString("std_dept"));
                src_cgpa.setText(rs.getString("std_cgpa"));
                src_credit.setText(rs.getString("std_credit"));
                
                
            //}
        }
        catch(Exception e){
            src_note.setText("Sorry, no student found.");
                    // TODO add your handling code here:
                //search_std_id.setText("");
                name.setText("");
                dept.setText("");
                id.setText("");
                cgpa.setText("");
                credit.setText("");
                src_name.setText("");
                src_dept.setText("");
                src_id.setText("");
                src_cgpa.setText("");
                src_credit.setText("");
        }
    }//GEN-LAST:event_panal1_button_searchActionPerformed

    private void panal1_button_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal1_button_searchMouseEntered
        // TODO add your handling code here:
        panal1_button_search.setBackground(new java.awt.Color(150,190,204));
    }//GEN-LAST:event_panal1_button_searchMouseEntered

    private void panal1_button_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panal1_button_searchMouseExited
        // TODO add your handling code here:
        panal1_button_search.setBackground(new java.awt.Color(156,160,252));
    }//GEN-LAST:event_panal1_button_searchMouseExited

    private void add_std_idCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_add_std_idCaretUpdate
        // TODO add your handling code here:
        System.out.println(add_std_id.getText());
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://sql6.freesqldatabase.com:3306/sql6518757","sql6518757","jXZABmjPLt");
            ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://localhost:3306/project_sms","root","2580");
            StatementImpl st= (StatementImpl)conn.createStatement();
            String sql="select * from student where std_id='" + add_std_id.getText() +"'";//select * from admin where username='sdd'
            ResultSet rs=st.executeQuery(sql);
            //while(rs.next()){ // no need while loop cause there are condition in query username='user' 
            rs.next();
                String std_name,std_dept;
                std_name = rs.getString("std_name");
                std_dept = rs.getString("dept");
                //System.out.println(std_name+" "+std_dept);
                add_std_name.setText(std_name);
                System.out.println("Name = "+std_name);
                add_std_dept.setSelectedItem(std_dept);
                add_std_note.setText("Student alrady exist.");
            //}
        }
        catch(Exception e){
            add_std_note.setText(" ");
        }
    }//GEN-LAST:event_add_std_idCaretUpdate

    private void search_std_idCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_search_std_idCaretUpdate
        // TODO add your handling code here:
                        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://sql6.freesqldatabase.com:3306/sql6518757","sql6518757","jXZABmjPLt");
            ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://localhost:3306/project_sms","root","2580");
            StatementImpl st= (StatementImpl)conn.createStatement();
            String sql="select * from student where std_id='" + search_std_id.getText() +"'";//select * from admin where username='sdd'
            ResultSet rs=st.executeQuery(sql);
            //while(rs.next()){ // no need while loop cause there are condition in query username='user' 
            rs.next();

                //System.out.println(std_name+" "+std_dept);
                src_name.setText(rs.getString("std_name"));
                src_dept.setText(rs.getString("std_id"));
                src_id.setText(rs.getString("dept"));
                src_cgpa.setText(rs.getString("std_cgpa"));
                src_credit.setText(rs.getString("std_credit"));
                name.setText("Name :");
                dept.setText("Dept :");
                id.setText("ID :");
                cgpa.setText("CGPA :");
                credit.setText("Credit :");

            //}
        }
        catch(Exception e){
            src_note.setText("");
                    // TODO add your handling code here:
                search_std_id.setText("");
                name.setText("");
                dept.setText("");
                id.setText("");
                cgpa.setText("");
                credit.setText("");
                src_name.setText("");
                src_dept.setText("");
                src_id.setText("");
                src_cgpa.setText("");
                src_credit.setText("");
        }
    }//GEN-LAST:event_search_std_idCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                search_std_id.setText("");
                name.setText("");
                dept.setText("");
                id.setText("");
                cgpa.setText("");
                credit.setText("");
                src_name.setText("");
                src_dept.setText("");
                src_id.setText("");
                src_cgpa.setText("");
                src_credit.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_std_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_std_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_std_deptActionPerformed
    void admin(){
        setEnabled(false);
        login user=new login();
        user.setVisible(true);
        while(!user.admin);
        setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JLabel add_labal1;
    JComboBox<String> add_std_dept;
    JTextField add_std_id;
    JTextField add_std_name;
    JLabel add_std_note;
    JButton add_student;
    JPanel banner;
    JPanel jPanel2;
    JLabel cgpa;
    JLabel credit;
    JLabel dept;
    JPanel jPanel1;
    JLabel id;
    JButton jButton1;
    JLabel jLabel1;
    JLabel jLabel2;
    JLabel jLabel3;
    JLabel l_result;
    JLabel jLabel7;
    JPanel jPanel1;
    JPanel jPanel2;
    JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    JPanel main_menu;
    JLabel name;
    JButton panal1_button_search;
    private java.awt.Panel panel_add;
    private java.awt.Panel panel_search;
    JTextField search_std_id;
    JLabel src_cgpa;
    JLabel src_credit;
    JLabel src_dept;
    JLabel src_id;
    JLabel src_name;
    JLabel src_note;
    // End of variables declaration//GEN-END:variables
}


/*

try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://localhost:3306/project_sms","root","2580");
            String sql="insert into `student`(`std_id`, `std_name`, `std_dept`) values(?,?,?)";
            PreparedStatement ps = conn.prepareStatement(sql);
        }
        catch(Exception e){
            add_std_note.setText("Sorry something went wrong.");
        }
    } 

*/