/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package student_management_system.body;

import java.awt.Color;
import javax.swing.JMenuItem;
import student_management_system.Server;
import student_management_system.course;

/**
 *
 * @author sdd
 */
public class course_offer_panel extends javax.swing.JPanel {
    public String dept,code,title,credit,teacher;
    /**
     * Creates new form course_offer_panel
     */
    public course_offer_panel() {
        initComponents();  
        code_box.setSelectedItem(null);
        teacher_box.setSelectedItem(null);
    }
    public void update(){
        code_box.setModel(Server.get_course_list(dept));
        code_box.setSelectedItem(null);
        teacher_box.setSelectedItem(null);
    }
    public void reg(String session,String dept,String semester){
        if(status.isSelected())
            Server.course_offer_reg(session, dept, semester, code_box.getSelectedItem().toString(), teacher_box.getSelectedItem().toString());
    }
    public void clear(){
        code_box.setSelectedItem(null);
        tittle_box.setText("");
        credit_box.setText("");
        teacher_box.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void tittle(){
        
    }
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        code_box = new javax.swing.JComboBox<>();
        tittle_box = new javax.swing.JTextField();
        credit_box = new javax.swing.JTextField();
        teacher_box = new javax.swing.JComboBox<>();
        status = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        code_box.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        code_box.setModel(Server.get_course_list(dept));
        code_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_boxActionPerformed(evt);
            }
        });
        code_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                code_boxKeyPressed(evt);
            }
        });

        tittle_box.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tittle_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tittle_boxActionPerformed(evt);
            }
        });

        credit_box.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N

        teacher_box.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        teacher_box.setModel(Server.get_table_column("teacher","name"));

        status.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(code_box, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tittle_box, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(credit_box, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacher_box, 0, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(code_box, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tittle_box, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(credit_box, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(teacher_box, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tittle_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tittle_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tittle_boxActionPerformed

    private void code_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code_boxActionPerformed
        // TODO add your handling code here:
        code= (String) code_box.getSelectedItem();
        course crs=new course(code);
        if(crs.status)
        {
            tittle_box.setText(crs.tittle);
            credit_box.setText(crs.credit);
        }
        else
        {
            tittle_box.setText("");
            credit_box.setText("");
        }
    }//GEN-LAST:event_code_boxActionPerformed

    private void code_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_code_boxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_code_boxKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> code_box;
    private javax.swing.JTextField credit_box;
    public javax.swing.JPopupMenu popup;
    private javax.swing.JCheckBox status;
    private javax.swing.JComboBox<String> teacher_box;
    private javax.swing.JTextField tittle_box;
    // End of variables declaration//GEN-END:variables
}
