/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package student_management_system.body; 

import javax.swing.*;
import com.mysql.cj.jdbc.ConnectionImpl;
import com.mysql.cj.jdbc.StatementImpl;
import java.awt.Color;
import java.awt.Font;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import student_management_system.EvenOddRenderer;
import student_management_system.student;
import student_management_system.teacher;
import student_management_system.user;

/**
 *
 * @author sdddd
 */
public class student_approval extends javax.swing.JInternalFrame {
javax.swing.JDesktopPane bPane;
user u;
teacher t;
    /**
     * Creates new form menu1
     */
    public student_approval(javax.swing.JDesktopPane bPane,user u) {
        initComponents();
        this.setBorder (javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); 
        //BasicInternalFrameUI ui = 
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI(); 
        ui.setNorthPane (null);
        this.bPane=bPane;
        this.setSize(bPane.getSize());
        this.u=u;
        this.t=u.user_teacher;
        table_std.getTableHeader().setFont(new Font("Noto Mono", Font.BOLD,18));
        table_std.getTableHeader().setOpaque(false);
        table_std.getTableHeader().setBackground(new Color(255,255,255));
        table_std.getTableHeader().setForeground(new Color(255,0,0));
        table_std.getTableHeader().setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        TableCellRenderer renderer = new EvenOddRenderer();
        table_std.setDefaultRenderer(Object.class, renderer);
        update_table();
        table_std.setBorder(null);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
    }

    private void update_table()
    {
        System.out.println("update table");
        DefaultTableModel new_raw=(DefaultTableModel)table_std.getModel();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionImpl conn=(ConnectionImpl)DriverManager.getConnection("jdbc:mysql://localhost:3306/project_sms","root","2580");
            StatementImpl st= (StatementImpl)conn.createStatement();
            String sql="select * from student where reg_status='Pending'";//select * from admin where username='sdd'
            System.out.println(sql);
            ResultSet rs=st.executeQuery(sql);
            new_raw.setRowCount(0);
            while(rs.next())
            {
                String str[]={rs.getString("std_id"),rs.getString("std_name"),rs.getString("dept")};
                new_raw.addRow(str);
                //System.out.println(str[0]+" "+str[1]);
            }
            int r= table_std.getRowCount();
            for(int i=0;i<18-r;i++)
            {
                String str[]={" "," "," "," "};
                new_raw.addRow(str);
            }
            //System.out.println(bPane2.getSize());            
        }              
        catch(Exception e){
            System.out.println("Server error");
        }
     } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        table_std = new JTable();
        jLabel1 = new JLabel();
        jButton1 = new JButton();

        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table_std.setFont(new java.awt.Font("Nakula", 1, 20));  
        table_std.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"hgjkjkjjk", "jhkhj", "uh"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Dept"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_std.setGridColor(new java.awt.Color(255, 255, 255));
        table_std.setRowHeight(40);
        table_std.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_stdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_std);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(my.font2);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Approval");

        jButton1.setFont(my.font);
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        // TODO add your handling code here:
        this.setSize(bPane.getSize());
    }//GEN-LAST:event_formAncestorResized

    private void table_stdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_stdMouseClicked
        // TODO add your handling code here:
        int column = 0;
        int row = table_std.getSelectedRow();
        String value = table_std.getModel().getValueAt(row, column).toString();
        System.out.println("id : "+value);
        student std=new student(value);
        student_details obj=new student_details(bPane,u,std);
        bPane.add(obj).setVisible(true);
    }//GEN-LAST:event_table_stdMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        bPane.remove(this);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton jButton1;
    JLabel jLabel1;
    JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_std;
    // End of variables declaration//GEN-END:variables
}
